accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('<slug:course_slug>/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson-detail'), # <slug:course_slug>/lessons/<slug:slug>/
]

elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('courses/', include('courses.urls'), name='courses'),
]

accounts/models.py
from django.db import models

# Create your models here.

courses/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.last_name  + ' ' + self.first_name


class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    summary = models.CharField(max_length=255, null=True, blank=True)
    # technology = models.CharField(max_length=100)
    # logo = models.CharField(max_length=1000)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('courses:course-detail', args=[str(self.slug)]) # kwargs={'pk': self.pk}

    def __str__(self):
        return self.title + ' ' + str(self.author)


class Module(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    course = models.ForeignKey(Course, related_name="modules", on_delete=models.CASCADE) # null=False, blank=False

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    module = models.ForeignKey(Module, related_name='lessons', on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)

    class Meta:
        ordering = ['pk']

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={'course_slug': self.module.course.slug, 'slug': self.slug})

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

courses/views.py
from django.views import generic
from .models import Course, Module, Lesson
# from django.contrib.auth.mixins import LoginRequiredMixin
# https://docs.djangoproject.com/en/2.1/topics/auth/default/#the-loginrequired-mixin

# Create your views here.

class IndexView(generic.ListView):
    # login_url = 'login'
    # redirect_field_name = 'redirect_to'

    template_name = 'courses/index.html'

    # the default is object_list, but we want to use all_courses inside the views.py file
    # context_object_name = 'course_list'

    def get_queryset(self):
        return Course.objects.all()

class CourseDetailView(generic.DetailView):
    model = Course
    # template_name = 'courses/course_detail.html'

class LessonDetailView(generic.DetailView):
    model = Lesson
    # template_name = 'courses/lesson_detail.html'

courses/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}I Dev TV{% endblock %}</title>
    <!-- Loading the path to our static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </head>

  <body>

    {% block content %}
    {% endblock %}

  </body>

</html>

courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block title %}Course Details{% endblock %}

{% block content %}

  <!-- <img src="{{ course.logo }}" /> -->
  <h1>{{ course.title }}</h1>
  <h3>{{ course.author }}</h3>

  {% if course.modules %}
    {% for module in course.modules.all %}
      <p><strong>{{ module }}</strong></p>
      {% if module.lessons %}
        {% for lesson in module.lessons.all %}
          <p><a href="{{ lesson.get_absolute_url }}">{{ lesson }}</a></p>
        {% endfor %}
      {% endif %}
    {% endfor %}
  {% else %}
    <p>No Module found...</p>
  {% endif %}

  <h3>URL: {{ course.get_absolute_url }}</h3>

  {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <!-- <ul>
    {% for lesson in course.lesson_set.all  %}
      <li>{{ lesson.title }} - {{ lesson.file_type }}</li>
    {% endfor %}
  </ul> -->

{% endblock %}

courses/templates/courses/detail.html
{% extends 'courses/base.html' %}

{% block title %}Course Details{% endblock %}

{% block content %}

  <!-- <img src="{{ course.logo }}" /> -->
  <h1>{{ course.title }}</h1>
  <h3>{{ course.author }}</h3>

  {% if course.modules %}
    {% for module in course.modules.all %}
      <p><strong>{{ module }}</strong></p>
      {% if module.lessons %}
        {% for lesson in module.lessons.all %}
          <p><a href="">{{ lesson }}</a></p>
        {% endfor %}
      {% endif %}
    {% endfor %}
  {% else %}
    <p>No Module found...</p>
  {% endif %}

  <h3>URL: {{ course.get_absolute_url }}</h3>

  {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <!-- <ul>
    {% for lesson in course.lesson_set.all  %}
      <li>{{ lesson.title }} - {{ lesson.file_type }}</li>
    {% endfor %}
  </ul> -->

{% endblock %}

courses/templates/courses/index.html
{% extends 'courses/base.html' %}

{% block title %}Courses | I Dev TV{% endblock %}

{% block content %}

  {% if course_list %}
    <!-- code here to list the courses -->
    <h1>List of courses here...</h1>
    <ul>
      {% for course in course_list %}
        <li>{{ course }} <a href="{% url 'courses:course-detail' course.slug %}">Go to Course</a></li>
        {% comment %} Similarly, we can use {{ course.get_absolute_url }} {% endcomment %}
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no courses available...</p>
  {% endif %}

{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block title %}Course Details{% endblock %}

{% block content %}

  <h1>{{ lesson.title }}</h1>
  <h3>{{ lesson.module }}</h3>


  <h3>URL: {{ lesson.get_absolute_url }} | pk = {{ lesson.pk }}</h3>

  {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
  {% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}I Dev TV{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home | I Dev TV{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}